CREATE DATABASE misc;
GRANT ALL ON misc.* TO 'dan'@'localhost' IDENTIFIED BY 'php123';
GRANT ALL ON misc.* TO 'dan'@'127.0.0.1' IDENTIFIED BY 'php123';

DROP TABLE IF EXISTS auto;
CREATE TABLE auto (
	auto_id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT KEY,
	imageURL VARCHAR(255)
	make VARCHAR(128),
    model VARCHAR(255),
	year INTEGER,
	mileage INTEGER
);

ALTER TABLE auto
ADD COLUMN imageURL VARCHAR(255) AFTER auto_id;

ALTER TABLE auto AUTO_INCREMENT = x;

ALTER TABLE misc
ADD COLUMN model VARCHAR(255)
AFTER make;